# print only error messages
debug = true

logLevel = "INFO"

# allow ingress trafic on port 80 and 443
# redirect trafic from port 80 to 443
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

# retry request when network errors apear; default 3 times
[retry]

# enable traefik dashboard on port 8080
[api]

# enable traefik to discover new container by their traefik-labels on your docker host
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "ht.iostw.com"
watch = true
exposedByDefault = false

# enable the acme to issue Let's Encrypt SSL-Certificates
[acme]
email = "robertklein.sk@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"